# Generated by Django 4.0.4 on 2022-06-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_usuario',
            name='profile_image',
            field=models.ImageField(default=' ', upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
