# Generated by Django 4.0.4 on 2022-06-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_perfil_usuario_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil_usuario',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
