# Generated by Django 4.0.4 on 2022-06-30 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_perfil_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil_usuario',
            options={},
        ),
    ]
