# Generated by Django 4.0.4 on 2022-06-26 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_local_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.categoria'),
            preserve_default=False,
        ),
    ]
